spring.application.name=splitkro

spring.datasource.url=jdbc:mysql://root:GwyTkZxOHDfBYogIKZpkzFLFQKvKisxm@crossover.proxy.rlwy.net:13923/railway
spring.datasource.username=root
spring.datasource.password=GwyTkZxOHDfBYogIKZpkzFLFQKvKisxm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT - set this in Railway environment variables
jwt.secret=thisIsAVeryLongSecretKeyForSplitKroAppThatIsAtLeast256BitsLong
jwt.expiration=86400000


# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

server.port=${PORT:8080}