spring.application.name=splitkro

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT - set this in Railway environment variables
jwt.secret=thisIsAVeryLongSecretKeyForSplitKroAppThatIsAtLeast256BitsLong
jwt.expiration=86400000


# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
